name: test-and-deploy

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install --ignore-scripts
      - run: npm run lint

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master' || 'refs/heads/asyncglk'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Get Emglken commit ref
        id: emglken-ref
        run: echo "::set-output name=ref::$(git submodule status src/upstream/emglken | cut -c 2-13)"
      - name: Cache the built Emglken
        id: cache-emglken
        uses: actions/cache@v2
        with:
          path: src/upstream/emglken/build
          key: emglken-${{ steps.emglken-ref.outputs.ref }}
      - run: npm install --ignore-scripts
      - run: npm run link-local-emglken
      - name: Build AsyncGlk
        if: github.ref == 'refs/heads/asyncglk'
        run: cd src/upstream/asyncglk && npm install && npx tsc
      - name: Build Emglken
        if: steps.cache-emglken.outputs.cache-hit != 'true'
        run: cd src/upstream/emglken && npm run build
      - run: npm run gulp
      - name: Package Parchment for Inform 7
        if: github.ref == 'refs/heads/master'
        run: npm run inform7
      - run: cp tools/deploy.gitignore .gitignore
      - name: Deploy to Pages 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
      - name: Deploy to testing site 🚀
        if: github.ref == 'refs/heads/asyncglk'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: false
          folder: .
          repository-name: ${{ secrets.PARCHMENT_TESTING_REPO }}
          token: ${{ secrets.PARCHMENT_TESTING_TOKEN }}